Split up lines in git config
Now that the bugged mac git complation is worked around

diff --git a/git-config b/git-config
--- a/git-config
+++ b/git-config
@@ -121,10 +121,42 @@ EOF
 git config --global alias.subject-length '!f() { git log -1 --format="%s" | tr -d "\n" | wc -m; }; f'
 
 # Stash only staged changes
-git config --global alias.stash-staged '!f() { staged="$(git diff --staged --unified=0)"; unstaged="$(git diff --unified=0)"; [ "$staged" = "" ] && return; [ "$unstaged" = "" ] && { git stash "$@"; return "$?"; }; printf "This is a potentially destructive command.\nBe sure you understand it before running it.\nContinue? [y/N]: "; IFS= read -r cont; echo "$cont" | grep -iq "^y" || { echo "Not continuing."; return 1; }; git reset --hard && echo -E "$staged" | git apply --unidiff-zero - && git stash "$@" && echo -E "$unstaged" | git apply --unidiff-zero - || { top="$(git rev-parse --git-dir)"; echo -E "$staged" >"$top/LAST_STAGED.diff"; echo -E "$unstaged" >"$top/LAST_UNSTAGED.diff"; printf "\x1b[0;31mERROR:\x1b[0m Could not stash staged.\nDiffs saved: try git apply --unidiff-zero .git/LAST_STAGED.diff .git/LAST_UNSTAGED.diff\n"; }; }; f'
+git config --global alias.stash-staged '!f() {
+    staged="$(git diff --staged --unified=0)";
+    unstaged="$(git diff --unified=0)";
+    [ "$staged" = "" ] && return;
+    [ "$unstaged" = "" ] && { git stash "$@"; return "$?"; };
+    printf "This is a potentially destructive command.\nBe sure you understand it before running it.\nContinue? [y/N]: ";
+    IFS= read -r cont; echo "$cont" | grep -iq "^y" || { echo "Not continuing."; return 1; };
+    git reset --hard &&
+        echo -E "$staged" | git apply --unidiff-zero - &&
+        git stash "$@" &&
+        echo -E "$unstaged" | git apply --unidiff-zero - || {
+            top="$(git rev-parse --git-dir)";
+            echo -E "$staged" >"$top/LAST_STAGED.diff";
+            echo -E "$unstaged" >"$top/LAST_UNSTAGED.diff";
+            printf "\x1b[0;31mERROR:\x1b[0m Could not stash staged.\nDiffs saved: try git apply --unidiff-zero .git/LAST_STAGED.diff .git/LAST_UNSTAGED.diff\n";
+        };
+}; f'
 
 # Stash only unstaged changes
-git config --global alias.stash-unstaged '!f() { staged="$(git diff --staged --unified=0)"; unstaged="$(git diff --unified=0)"; [ "$staged" = "" ] && { git stash "$@"; return "$?"; }; [ "$unstaged" = "" ] && return; printf "This is a potentially destructive command.\nBe sure you understand it before running it.\nContinue? [y/N]: "; IFS= read -r cont; echo "$cont" | grep -iq "^y" || { echo "Not continuing."; return 1; }; git reset --hard && echo -E "$unstaged" | git apply --unidiff-zero - && git stash "$@" && echo -E "$staged" | git apply --unidiff-zero - || { top="$(git rev-parse --git-dir)"; echo -E "$staged" >"$top/LAST_STAGED.diff"; echo -E "$unstaged" >"$top/LAST_UNSTAGED.diff"; printf "\x1b[0;31mERROR:\x1b[0m Could not stash unstaged.\nDiffs saved: try git apply --unidiff-zero .git/LAST_STAGED.diff .git/LAST_UNSTAGED.diff\n"; }; }; f'
+git config --global alias.stash-unstaged '!f() {
+    staged="$(git diff --staged --unified=0)";
+    unstaged="$(git diff --unified=0)";
+    [ "$staged" = "" ] && { git stash "$@"; return "$?"; };
+    [ "$unstaged" = "" ] && return;
+    printf "This is a potentially destructive command.\nBe sure you understand it before running it.\nContinue? [y/N]: ";
+    IFS= read -r cont; echo "$cont" | grep -iq "^y" || { echo "Not continuing."; return 1; };
+    git reset --hard && echo -E "$unstaged" |
+        git apply --unidiff-zero - &&
+        git stash "$@" &&
+        echo -E "$staged" | git apply --unidiff-zero - || {
+            top="$(git rev-parse --git-dir)";
+            echo -E "$staged" >"$top/LAST_STAGED.diff";
+            echo -E "$unstaged" >"$top/LAST_UNSTAGED.diff";
+            printf "\x1b[0;31mERROR:\x1b[0m Could not stash unstaged.\nDiffs saved: try git apply --unidiff-zero .git/LAST_STAGED.diff .git/LAST_UNSTAGED.diff\n";
+        };
+}; f'
 
 # Press enter to view a stash's diff, q to exit the diff pager, and esc to exit fzf
 git config --global alias.stash-browse '!f() {
